inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 4

FactoryBot/AttributeDefinedStatically:
  Enabled: true
