default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME_DEVELOPMENT"] || "instarails_development" %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] || "instarails_test" %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME_PRODUCTION"] || "instarails_production" %>
